"""
Garage's administration API — creating a course's bucket and granting the
ingest key on it.

Not the `garage` CLI. That runs inside the storage container and is reached
with `docker exec`, which means the Content Admin would need the Docker
socket: a container that can start containers is a container that can do
anything on the host, in exchange for creating a bucket. The admin API is
reachable over the ordinary Docker network on port 3903 and is exactly as
capable for this.

Endpoints and payloads are v2 (Garage v2.3.0), taken from the published
OpenAPI document rather than from memory — v1 spelled them differently and
the two are not interchangeable:

    POST /v2/CreateBucket    {"globalAlias": "<name>"}
    GET  /v2/GetBucketInfo?globalAlias=<name>
    POST /v2/AllowBucketKey  {"bucketId", "accessKeyId",
                              "permissions": {"read", "write", "owner"}}

Garage has no bucket policies and no root user: a key is granted per bucket,
which is why creating a course is two calls and not one.
"""

import logging
import os

import requests

from env_file import read_env

logger = logging.getLogger(__name__)

TIMEOUT = 15


class GarageError(RuntimeError):
    """Raised with Garage's own answer attached. The admin API says useful
    things in its error bodies and paraphrasing them loses the useful part."""


class GarageClient:
    def __init__(self, base_url: str = "", token: str = ""):
        env = read_env()
        self.base = (base_url
                     or os.getenv("SMARTRAG_GARAGE_ADMIN_URL",
                                  "http://smartrag-garage:3903")).rstrip("/")
        self.token = token or env.get("GARAGE_ADMIN_TOKEN", "").strip()
        if not self.token:
            raise GarageError(
                "GARAGE_ADMIN_TOKEN is missing from .env, so buckets cannot be "
                "created. It is generated by the installer; sudo smartrag → "
                "Upgrade fills it in on an installation that predates it."
            )

    # ─── internals ──────────────────────────────────────────────────────────
    def _request(self, method: str, path: str, **kwargs):
        url = f"{self.base}{path}"
        headers = {"Authorization": f"Bearer {self.token}"}
        headers.update(kwargs.pop("headers", {}))
        try:
            resp = requests.request(method, url, headers=headers,
                                    timeout=TIMEOUT, **kwargs)
        except requests.RequestException as exc:
            raise GarageError(f"{method} {path} failed: {exc}") from exc

        if resp.status_code == 404:
            return None
        if not resp.ok:
            raise GarageError(
                f"{method} {path} → HTTP {resp.status_code}: {resp.text[:300]}"
            )
        if not resp.content:
            return {}
        try:
            return resp.json()
        except ValueError:
            return resp.text

    # ─── buckets ────────────────────────────────────────────────────────────
    def bucket_info(self, name: str) -> dict | None:
        """The bucket, or None when it does not exist."""
        return self._request("GET", "/v2/GetBucketInfo",
                             params={"globalAlias": name})

    def create_bucket(self, name: str) -> dict:
        """Create it, or return the existing one.

        Idempotent on purpose: provisioning a course is re-runnable after a
        partial failure, and a second attempt must not fail on the half that
        already succeeded.
        """
        existing = self.bucket_info(name)
        if existing:
            return existing
        created = self._request("POST", "/v2/CreateBucket",
                                json={"globalAlias": name})
        if not created:
            raise GarageError(f"Garage did not return the bucket it created: {name}")
        return created

    def allow_key(self, bucket_id: str, access_key_id: str,
                  read: bool = True, write: bool = True, owner: bool = True) -> None:
        """Grant a key on a bucket. Also idempotent — granting twice is a
        no-op to Garage, and re-running provisioning must be safe."""
        self._request("POST", "/v2/AllowBucketKey", json={
            "bucketId": bucket_id,
            "accessKeyId": access_key_id,
            "permissions": {"read": read, "write": write, "owner": owner},
        })

    def delete_bucket(self, name: str) -> bool:
        """Remove a bucket. True when it was there, False when it was not.

        Garage refuses a bucket that still holds objects, and its admin API
        has no way to remove them — that is what s3_client exists for. The
        refusal is deliberately not translated into something softer here: a
        bucket that survives a course deletion is a bucket the next course of
        the same name would silently adopt, because create_bucket is
        idempotent.
        """
        info = self.bucket_info(name)
        if info is None:
            return False
        bucket_id = info.get("id")
        if not bucket_id:
            raise GarageError(f"Garage returned no id for bucket {name}.")
        self._request("POST", "/v2/DeleteBucket", params={"id": bucket_id})
        return True

    def key_can_write(self, name: str, access_key_id: str) -> bool:
        """Whether that key actually has write on that bucket.

        Used to verify provisioning rather than to assume it: a bucket that
        exists and a key that exists still store nothing if the grant between
        them is missing, and that failure is silent at write time.
        """
        info = self.bucket_info(name)
        if not info:
            return False
        for key in info.get("keys", []):
            if key.get("accessKeyId") == access_key_id:
                perms = key.get("permissions", {})
                return bool(perms.get("write"))
        return False
