#!/usr/bin/env bash
# What .gitignore claims to exclude, and what it actually excludes.
#
# Found on the test server, in the working tree, untracked and therefore one
# `git add -A` away from GitHub:
#
#     credentials.txt          # generated by bootstrap.sh — contains initial passwords
#
# In .gitignore a '#' begins a comment **only at the start of a line**. On any
# other line it is an ordinary character, so that pattern was not
# "credentials.txt" — it was the whole sentence, which matches no file that
# will ever exist. The rule had been there since the beginning and had never
# once worked. bootstrap.sh writes the initial passwords for Postgres, Neo4j,
# ClickHouse, Flowise and the Content Admin into that file.
#
# Nothing leaked: `git log --all -- credentials.txt` is empty. This project has
# leaked real keys once before, by checking two of several blocks and
# generalising, so the checks below are exhaustive rather than a sample: every
# pattern line is tested for the inline-comment shape, and every secret-bearing
# file this repository's own scripts create is tested by name against the real
# `git check-ignore`, not by reading the file.
set -uo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO" || exit 1
FAILURES=()
check() { if (( $2 != 0 )); then FAILURES+=("$1: $3"); fi; }

# ─── No pattern may carry a trailing comment ────────────────────────────────
# An escaped \# is a literal '#' in a filename and is legitimate; nothing else
# after a pattern is.
broken="$(grep -nE '^[^#].*[^\\]#' .gitignore || true)"
[[ -z "$broken" ]]
check "no pattern line carries an inline comment" $? \
      "these match nothing at all: ${broken//$'\n'/ | }"

# ─── Every secret this repo's own scripts write is ignored ──────────────────
# Names, not guesses: each is created by the script named beside it.
while read -r path origin; do
    [[ -z "$path" ]] && continue
    git check-ignore -q "$path"
    check "$path is ignored" $? "written by $origin, and git would offer it"
done <<'PATHS'
.env                                            bootstrap.sh
.env.backup-2026-01-01                          write_env / templates.sh
credentials.txt                                 bootstrap.sh
server.key                                      nginx / TLS setup
server.pem                                      nginx / TLS setup
host.example.ts.net.crt                         tailscale cert
host.example.ts.net.csr                         TLS setup
lti-middleware/config/lti.json                  LTI configuration
lti-middleware/config/agents.json               LTI configuration
sub/dir/.env                                    any nested install
PATHS

# ─── And none of them is tracked already ────────────────────────────────────
# check-ignore says nothing about a file that is already in the index: an
# ignore rule does not untrack anything.
tracked="$(git ls-files | grep -E '(^|/)(\.env|credentials\.txt)$|\.(key|pem|crt|csr)$' || true)"
[[ -z "$tracked" ]]
check "no secret-bearing file is tracked" $? "${tracked//$'\n'/ | }"

# ─── Nor in any commit that ever existed ────────────────────────────────────
histor="$(git log --all --pretty=format: --name-only \
          -- '.env' '**/.env' 'credentials.txt' '*.key' '*.pem' '*.crt' \
          | sort -u | grep -v '^$' || true)"
[[ -z "$histor" ]]
check "and none was ever committed" $? \
      "rewriting history is not enough — rotate what is in ${histor//$'\n'/ | }"

if (( ${#FAILURES[@]} > 0 )); then
    echo "FAILURES:"; printf '  - %s\n' "${FAILURES[@]}"; exit 1
fi
echo "All .gitignore checks passed: no pattern carries a trailing comment — the"
echo "shape that silently disabled the credentials.txt rule for the whole life"
echo "of the repository — every secret-bearing file this project's own scripts"
echo "write is ignored under its real name, none of them is tracked, and none"
echo "appears in any commit that has ever existed."
