#!/usr/bin/env bash
# ═════════════════════════════════════════════════════════════════════════════
# SMART RAG — Obtain SSL certificates via Let's Encrypt (Phase 6)
# ═════════════════════════════════════════════════════════════════════════════
#
# Issues one multi-domain (SAN) certificate covering all required subdomains.
# Uses webroot challenge — no nginx downtime.
#
# Reads from .env:  DOMAIN, ADMIN_EMAIL, COMPOSE_PROFILES
#
# Flow:
#   1. Verify all required subdomains resolve to this server's public IP.
#   2. Write a minimal HTTP-only nginx config that serves /.well-known/.
#   3. Reload nginx (now ACME challenges are served).
#   4. Run certbot certonly --webroot (one SAN cert for all subdomains).
#   5. Replace the temp config with the full HTTP + HTTPS smart-rag.conf
#      (already generated by bootstrap.sh phase 4).
#   6. Reload nginx (now HTTPS is live).
#
# Usage:  sudo bash scripts/get-ssl-certs.sh [--lang en|de] [--dry-run]
#
# Re-runnable: existing certs are detected and renewal is invoked via certbot.
# ═════════════════════════════════════════════════════════════════════════════

set -euo pipefail

if (( BASH_VERSINFO[0] < 4 )); then
    echo "ERROR: bash >= 4 required" >&2; exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LIB_DIR="$SCRIPT_DIR/lib"

# shellcheck source=lib/common.sh
source "$LIB_DIR/common.sh"
# shellcheck source=lib/messages.sh
source "$LIB_DIR/messages.sh"

# ─── Arg parsing ─────────────────────────────────────────────────────────────
DRY_RUN=0
while (( $# > 0 )); do
    case "$1" in
        --lang) shift; LANG_CHOICE="${1:-en}" ;;
        --lang=*) LANG_CHOICE="${1#*=}" ;;
        --dry-run) DRY_RUN=1 ;;
        *) die "Unknown argument: $1" ;;
    esac
    shift
done
LANG_CHOICE="${LANG_CHOICE:-$(detect_default_language)}"
export LANG_CHOICE

# ─── Root check ──────────────────────────────────────────────────────────────
if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    die "$(t pf_root_needed "$(basename "$0")")"
fi

# ─── Load .env ───────────────────────────────────────────────────────────────
[[ -f "$REPO_ROOT/.env" ]] || die "$(t orch_phase1_needed)"
set -a
# shellcheck source=/dev/null
source "$REPO_ROOT/.env"
set +a

# Required commands
require_command nginx
require_command certbot
require_command dig
require_command curl

header "$(t phase_ssl)"

# ─── Build subdomain list from profiles ──────────────────────────────────────
SUBDOMAINS=(
    "smart-rag.$DOMAIN"
    "n8n.$DOMAIN"
    "minio.$DOMAIN"
    "s3.$DOMAIN"
)
[[ "${COMPOSE_PROFILES:-core}" == *observability* ]] && SUBDOMAINS+=("langfuse.$DOMAIN")
[[ "${COMPOSE_PROFILES:-core}" == *lti*           ]] && SUBDOMAINS+=("lti.$DOMAIN")

info "$(t ssl_subdomain_list "${SUBDOMAINS[*]}")"

# ─── Detect server's public IP ───────────────────────────────────────────────
info "$(t ssl_resolving_server_ip)"
SERVER_IP="$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo "")"
[[ -n "$SERVER_IP" ]] || die "Could not detect public IP. Are you on the actual server?"
ok "$(t ssl_server_ip "$SERVER_IP")"

# ─── Verify DNS for each subdomain ───────────────────────────────────────────
info "$(t ssl_checking_dns)"
dns_failures=0
for sub in "${SUBDOMAINS[@]}"; do
    dns_ip="$(dig +short A "$sub" 2>/dev/null | head -1)"
    if [[ "$dns_ip" == "$SERVER_IP" ]]; then
        ok "$(t ssl_dns_match "$sub" "$dns_ip")"
    else
        err "$(t ssl_dns_fail "$sub" "${dns_ip:-<unresolved>}" "$SERVER_IP")"
        dns_failures=$((dns_failures+1))
    fi
done

if (( dns_failures > 0 )); then
    die "$(t ssl_dns_block "$SERVER_IP")"
fi

# Use a namespaced cert name to coexist safely with any existing certs.
# (e.g. an existing cert at /etc/letsencrypt/live/$DOMAIN/ stays untouched)
CERT_NAME="smartrag-$DOMAIN"
CERT_DIR="/etc/letsencrypt/live/$CERT_NAME"

if [[ -f "$CERT_DIR/fullchain.pem" ]]; then
    warn "$(t ssl_existing_cert "$CERT_NAME")"
fi

# ─── Step 1: Temporary ACME-only nginx config ────────────────────────────────
# Filenames are namespaced "smartrag-*" so we never overlap with anything
# the operator might have set up before.
ACME_CONF="/etc/nginx/sites-available/smartrag-acme.conf"
ACME_LINK="/etc/nginx/sites-enabled/smartrag-acme.conf"
FULL_CONF="/etc/nginx/sites-available/smartrag-suite.conf"
FULL_LINK="/etc/nginx/sites-enabled/smartrag-suite.conf"

if [[ ! -f "$FULL_CONF" ]]; then
    die "nginx config not found at $FULL_CONF — run scripts/bootstrap.sh first."
fi

info "$(t ssl_writing_acme_config)"
mkdir -p /var/www/html /etc/nginx/sites-available /etc/nginx/sites-enabled

cat > "$ACME_CONF" <<EOF
# Temporary ACME challenge config — replaced after certbot succeeds.
# Listens only on the smartrag-* subdomains, so any default-server or other
# nginx sites on port 80 keep working as before.
server {
    listen 80; listen [::]:80;
    server_name ${SUBDOMAINS[*]};
    location /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
    }
    location / {
        return 200 "SMART RAG — SSL setup in progress\n";
        add_header Content-Type text/plain;
    }
}
EOF

# IMPORTANT: We do NOT touch sites-enabled/default or any other existing config.
# Our temp ACME config has explicit server_name for our subdomains only;
# nginx will route those domains to us and everything else to whatever existed.
# Only the previous smartrag-suite.conf link (if any) is removed because it
# references certs that may not exist yet during the ACME challenge.
[[ -L "$FULL_LINK" ]] && rm -f "$FULL_LINK"
ln -sf "$ACME_CONF" "$ACME_LINK"

if ! nginx -t 2>&1 | tail -5; then
    die "nginx config test failed — see output above"
fi

info "$(t ssl_nginx_reload)"
systemctl reload nginx 2>/dev/null || systemctl start nginx

# ─── Step 2: Run certbot ─────────────────────────────────────────────────────
CERTBOT_ARGS=(
    certonly
    --webroot
    -w /var/www/html
    --cert-name "$CERT_NAME"
    --email "$ADMIN_EMAIL"
    --agree-tos
    --no-eff-email
    --non-interactive
    --keep-until-expiring
)
for sub in "${SUBDOMAINS[@]}"; do
    CERTBOT_ARGS+=(-d "$sub")
done

if (( DRY_RUN )); then
    CERTBOT_ARGS+=(--dry-run)
    warn "$(t ssl_dry_run "${SUBDOMAINS[*]}")"
fi

info "$(t ssl_requesting_cert)"
if certbot "${CERTBOT_ARGS[@]}"; then
    if (( DRY_RUN )); then
        ok "Dry-run successful — re-run without --dry-run to issue the real cert"
    else
        ok "$(t ssl_cert_obtained "$CERT_DIR/fullchain.pem")"
    fi
else
    die "certbot failed — see output above for details"
fi

# ─── Step 3: Swap to full nginx config (only if cert exists now) ─────────────
if [[ "$DRY_RUN" -eq 0 && -f "$CERT_DIR/fullchain.pem" ]]; then
    info "$(t ssl_installing_full_config)"
    rm -f "$ACME_LINK"
    ln -sf "$FULL_CONF" "$FULL_LINK"

    if ! nginx -t 2>&1 | tail -5; then
        # Revert
        rm -f "$FULL_LINK"; ln -sf "$ACME_CONF" "$ACME_LINK"
        die "Full nginx config failed validation — reverted to ACME-only"
    fi

    info "$(t ssl_nginx_reload)"
    systemctl reload nginx
    # Clean up the temp ACME config file (link already gone)
    rm -f "$ACME_CONF"
fi

ok "$(t ssl_done)"
